---
- name: Install Jenkins
  hosts: localhost
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  - name: Add Jenkins repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins
  - name: Update apt cache and install jenkins
    apt:
      name: jenkins
      update_cache: yes