---
- name: Install Grafana
  hosts: main
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started
  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu/
  - name: Unzip Prometheus
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu/
      remote_src: yes
  - name: Create Prometheus group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: Create Prometheus user
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin 
  - name: Create prometheus directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus
  - name: set perms
    ansible.builtin.file:
      path: "{{ item }}"
      mode: '0755'
    loop:
      - /etc/prometheus
      - /var/lib/prometheus
  - name: Copy files 
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      mode: '0755'
      owner: prometheus
      group: prometheus
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
  - name: Copy more files 
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries
